---
engines:
  rubocop:
    enabled: true
    checks:
      Rubocop/Style/FrozenStringLiteralComment:
        enabled: false
      Rubocop/Style/PercentLiteralDelimiters:
        enabled: false
      Rubocop/Lint/UnderscorePrefixedVariableName:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
        - ruby
exclude_paths:
- "benchmarks/**/*"
- "spec/**/*"
- "lib/tasks/**/*"
ratings:
   paths:
   - "lib/**/*"
